In [3]:
import pandas as pd

In [4]:
numbers = pd.Series([10, 20, 30, 40, 50])

In [5]:
numbers.map(lambda i: i**3)

0      1000
1      8000
2     27000
3     64000
4    125000
dtype: int64

In [6]:
numbers

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [7]:
~numbers.isin([20, 30])

0     True
1    False
2    False
3     True
4     True
dtype: bool

In [8]:
numbers[~numbers.isin([20, 30])]

0    10
3    40
4    50
dtype: int64

In [9]:
df = pd.read_excel("misthoi.xlsx", index_col="ID")
df.head()

ImportError: `Import openpyxl` failed.  Use pip or conda to install the openpyxl package.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 1 to 100
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Όνομα   100 non-null    object
 1   Ηλικία  100 non-null    int64
 2   Πόλη    100 non-null    object
 3   Μισθός  100 non-null    int64
dtypes: int64(2), object(2)
memory usage: 3.9+ KB

In [ ]:
df.describe()

           Ηλικία       Μισθός
count  100.000000   100.000000
mean    33.870000  1607.500000
std      5.459964    88.538926
min     26.000000  1470.000000
25%     29.000000  1550.000000
50%     33.000000  1600.000000
75%     38.000000  1680.000000
max     45.000000  1800.000000

In [ ]:
df.head()

NameError: name 'df' is not defined

In [10]:
%pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in ./.venv/lib/python3.13/site-packages (from seaborn) (2.4.2)
Requirement already satisfied: pandas>=1.2 in ./.venv/lib/python3.13/site-packages (from seaborn) (3.0.0)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Using cached matplotlib-3.10.8-cp313-cp313-macosx_11_0_arm64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached contourpy-1.3.3-cp313-cp313-macosx_11_0_arm64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached fonttools-4.61.1-cp313-cp313-macosx_10_13_universal2.whl.metadata (114 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached kiwisolver-1.4.9-cp313-cp313-macosx_11_0_arm64.whl.metadata (6.3 kB)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pillow-12.1.1-cp313-cp313-macosx_11_0_arm64.whl.metadata (8.8 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in ./.venv/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached matplotlib-3.10.8-cp313-cp313-macosx_11_0_arm64.whl (8.1 MB)
Using cached contourpy-1.3.3-cp313-cp313-macosx_11_0_arm64.whl (274 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.61.1-cp313-cp313-macosx_10_13_universal2.whl (2.8 MB)
Using cached kiwisolver-1.4.9-cp313-cp313-macosx_11_0_arm64.whl (64 kB)
Using cached pillow-12.1.1-cp313-cp313-macosx_11_0_arm64.whl (4.7 MB)
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [seaborn]m7/8 [seaborn]ib]
Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.61.1 kiwisolver-1.4.9 matplotlib-3.10.8 pillow-12.1.1 pyparsing-3.3.2 seaborn-0.13.2

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [11]:
import seaborn as sns

In [12]:
df = sns.load_dataset("tips")

In [13]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [15]:
df["tip"].sort_values(ascending=False)

170    10.00
212     9.00
23      7.58
59      6.73
141     6.70
       ...
0       1.01
236     1.00
111     1.00
67      1.00
92      1.00
Name: tip, Length: 244, dtype: float64

In [18]:
df.groupby("sex").agg({"tip": "sum", "size":"mean"})

           tip      size
sex
Male    485.07  2.630573
Female  246.51  2.459770

In [22]:
test = df.groupby(["sex", "smoker"])["tip"].agg("mean")
test

sex     smoker
Male    Yes       3.051167
        No        3.113402
Female  Yes       2.931515
        No        2.773519
Name: tip, dtype: float64

In [28]:
test.loc["Male", "Yes"]

np.float64(3.0511666666666666)

In [29]:
data = {
    "Department": ["Sales", "Sales", "HR", "HR", "IT", "IT"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Salary": [50000, 60000, 45000, 48000, 70000, 72000]
}

df = pd.DataFrame(data)

In [32]:
s_multi = df.groupby(["Department", "Employee"])["Salary"].sum()
s_multi

Department  Employee
HR          Charlie     45000
            David       48000
IT          Eva         70000
            Frank       72000
Sales       Alice       50000
            Bob         60000
Name: Salary, dtype: int64

In [33]:
s_multi.reset_index()

  Department Employee  Salary
0         HR  Charlie   45000
1         HR    David   48000
2         IT      Eva   70000
3         IT    Frank   72000
4      Sales    Alice   50000
5      Sales      Bob   60000