In [8]:
import pandas as pd

customers = pd.read_csv('data/customers.csv', usecols=["CustomerID", 'CustomerName', 'City'], index_col="CustomerID", dtype={"City": str})
customers

                       CustomerName         City
CustomerID
ALFKI                  Maria Anders       Berlin
ANATR                  Ana Trujillo  México D.F.
ANTON                Antonio Moreno  México D.F.
AROUT                  Thomas Hardy       London
BERGS            Christina Berglund        Luleå
...                             ...          ...
WARTH              Pirkko Koskitalo         Oulu
WELLI                 Paula Parente      Resende
WHITC                Karl Jablonski      Seattle
WILMK               Matti Karttunen     Helsinki
WOLZA       Zbyszek Piestrzeniewicz     Warszawa

[91 rows x 2 columns]

In [9]:
customers.loc['ANTON']

CustomerName    Antonio Moreno
City               México D.F.
Name: ANTON, dtype: str

# Accessing Data

In [11]:
customers.head(10)

                  CustomerName         City
CustomerID
ALFKI             Maria Anders       Berlin
ANATR             Ana Trujillo  México D.F.
ANTON           Antonio Moreno  México D.F.
AROUT             Thomas Hardy       London
BERGS       Christina Berglund        Luleå
BLAUS               Hanna Moos     Mannheim
BLONP       Frédérique Citeaux   Strasbourg
BOLID            Martín Sommer       Madrid
BONAP         Laurence Lebihan    Marseille
BOTTM        Elizabeth Lincoln    Tsawassen

In [12]:
customers.tail()

                       CustomerName      City
CustomerID
WARTH              Pirkko Koskitalo      Oulu
WELLI                 Paula Parente   Resende
WHITC                Karl Jablonski   Seattle
WILMK               Matti Karttunen  Helsinki
WOLZA       Zbyszek Piestrzeniewicz  Warszawa

In [13]:
customers.info()

<class 'pandas.DataFrame'>
Index: 91 entries, ALFKI to WOLZA
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerName  91 non-null     str
 1   City          91 non-null     str
dtypes: str(2)
memory usage: 4.2+ KB

In [14]:
order_details = pd.read_csv('data/orderdetails.csv')
order_details.head()

   OrderID  ProductID  Price  Quantity  Discount
0    10248         11   14.0        12       0.0
1    10248         42    9.8        10       0.0
2    10248         72   34.8         5       0.0
3    10249         14   18.6         9       0.0
4    10249         51   42.4        40       0.0

In [15]:
order_details.info()

<class 'pandas.DataFrame'>
RangeIndex: 2155 entries, 0 to 2154
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    2155 non-null   int64
 1   ProductID  2155 non-null   int64
 2   Price      2155 non-null   float64
 3   Quantity   2155 non-null   int64
 4   Discount   2155 non-null   float64
dtypes: float64(2), int64(3)
memory usage: 84.3 KB

In [16]:
order_details.describe()

            OrderID    ProductID        Price     Quantity     Discount
count   2155.000000  2155.000000  2155.000000  2155.000000  2155.000000
mean   10659.375870    40.793039    26.218520    23.812993     0.056167
std      241.378032    22.159019    29.827418    19.022047     0.083450
min    10248.000000     1.000000     2.000000     1.000000     0.000000
25%    10451.000000    22.000000    12.000000    10.000000     0.000000
50%    10657.000000    41.000000    18.400000    20.000000     0.000000
75%    10862.500000    60.000000    32.000000    30.000000     0.100000
max    11077.000000    77.000000   263.500000   130.000000     0.250000

In [17]:
customers.describe()

        CustomerName    City
count             91      91
unique            91      69
top     Maria Anders  London
freq               1       6